id: P003058
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4472
  title: སྤྱོད་འཇུག་རྣམ་བཤད་རྒྱལ་སྲས་འཇུག་ངོགས
  author: ''
  volumes:
    dab63bb9502040d4bd6a4bfea0657490:
      image_group_id: I1KG4499
      title: ''
      volume_number: 1
      total_pages: 308
